---
title: "Demonstration of WORCS UTU"
output: github_document
date: '`r format(Sys.time(), "%d %B, %Y")`'
bibliography: references.bib
knit: worcs::cite_all
---

```{r setup, include=FALSE}
library("worcs")
# We recommend that you prepare your raw data for analysis in 'prepare_data.R',
# and end that file with either open_data(yourdata), or closed_data(yourdata).
# Then, uncomment the line below to load the original or synthetic data
# (whichever is available), to allow anyone to reproduce your code:
load_data()
```



```{r descriptives}
res_desc <- descriptives(df)
write.csv(res_desc, "res_desc.csv", row.names = FALSE)
knitr::kable(res_desc[, c("name", "n", "mean", "sd")]) 
```


```{r model}
mod <- lm(bill_length_mm ~ species, data = df)
res_mod <- summary(mod)
write.csv(res_mod$coefficients, "res_coef.csv", row.names = FALSE)

knitr::kable(res_mod$coefficients, caption = "My regression model coefficients, for a model with $R^2 `r report(res_mod[['r.squared']])`$.")

#knitr::kable(res_mod[, c("name", "n", "mean", "sd")]) 


```

This manuscript uses the Workflow for Open Reproducible Code in Science [WORCS version 0.1.2, @vanlissaWORCSWorkflowOpen2021] to ensure reproducibility and transparency.


worcs::reproduce()
